# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='精确到秒', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='精确到秒', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除标识', verbose_name='删除标记')),
                ('mobile', models.CharField(help_text='要接收短信的号码,以";"分隔', max_length=1000, verbose_name='电话号码')),
                ('msg', models.CharField(help_text='短信内容', max_length=1000, verbose_name='短信内容')),
                ('equipment', models.CharField(help_text='要接收推送的设备类型,以";"分隔', max_length=30, verbose_name='推送设备')),
                ('sign_name', models.CharField(help_text='短信签名', max_length=30, verbose_name='短信签名')),
                ('result', models.CharField(blank=True, choices=[('success', '成功'), ('fail', '失败'), ('error', '错误')], help_text='success: 成功, fail: 失败, error: 错误', max_length=30, null=True, verbose_name='推送结果')),
                ('response_message', models.CharField(blank=True, help_text='服务平台返回的报文数据', max_length=300, null=True, verbose_name='返回报文')),
                ('secret_key', models.CharField(help_text='客户注册时生成的唯一密匙', max_length=36, verbose_name='密钥')),
            ],
            options={
                'verbose_name_plural': '推送记录',
                'db_table': 'push_record',
                'verbose_name': '推送记录',
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='精确到秒', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='精确到秒', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除标识', verbose_name='删除标记')),
                ('recharge_num', models.IntegerField(default=0, help_text='充值消息推送可用次数', verbose_name='充值数量')),
            ],
            options={
                'verbose_name_plural': '充值记录',
                'db_table': 'recharge_record',
                'verbose_name': '充值记录',
            },
        ),
    ]
