# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='client',
            field=models.ForeignKey(blank=True, help_text='被充值客户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recharge', to='user.Client', verbose_name='所属客户'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='提交操作人员', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_recharge', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='pushrecord',
            name='client',
            field=models.ForeignKey(blank=True, help_text='所属客户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_push', to='user.Client', verbose_name='所属客户'),
        ),
    ]
