# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-11 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20190710_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushrecord',
            name='equipment',
        ),
    ]
