# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20190711_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushrecord',
            name='mobile',
            field=models.CharField(help_text='要接收短信的号码', max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='pushrecord',
            name='result',
            field=models.CharField(blank=True, choices=[('success', '成功'), ('fail', '失败'), ('error', '错误'), ('debug', '测试')], help_text='success: 成功, fail: 失败, error: 错误', max_length=30, null=True, verbose_name='推送结果'),
        ),
    ]
