# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20190712_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushrecord',
            name='create_time',
            field=models.DateTimeField(help_text='精确到秒', verbose_name='创建时间'),
        ),
    ]
