# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20190712_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushrecord',
            options={'verbose_name': '短信记录', 'verbose_name_plural': '短信记录'},
        ),
        migrations.AddField(
            model_name='pushrecord',
            name='mobile_file',
            field=models.FileField(blank=True, help_text='要接收短信的号码文件', null=True, upload_to='mobile', verbose_name='电话号码文件'),
        ),
    ]
