# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20190722_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssign',
            name='response_message',
            field=models.CharField(blank=True, help_text='服务平台返回的报文数据', max_length=300, null=True, verbose_name='返回报文'),
        ),
        migrations.AddField(
            model_name='smssign',
            name='result',
            field=models.CharField(blank=True, choices=[('success', '成功'), ('fail', '失败'), ('error', '错误'), ('debug', '测试'), ('batch', '批量')], help_text='success: 成功, fail: 失败, error: 错误', max_length=30, null=True, verbose_name='推送结果'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='response_message',
            field=models.CharField(blank=True, help_text='服务平台返回的报文数据', max_length=300, null=True, verbose_name='返回报文'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='result',
            field=models.CharField(blank=True, choices=[('success', '成功'), ('fail', '失败'), ('error', '错误'), ('debug', '测试'), ('batch', '批量')], help_text='success: 成功, fail: 失败, error: 错误', max_length=30, null=True, verbose_name='推送结果'),
        ),
    ]
