# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-22 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20190722_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smstemplate',
            old_name='template_Content',
            new_name='template_content',
        ),
    ]
