"""
Django settings for sms_middleground project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(^gszve-zt$#de)r=m&m=t(f9kj@*tgeg^%!uhe*ma2m=c#+02'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 跨域问题
    'crispy_forms',  # xadmin
    'xadmin',  # xadmin
    'django_filters',  # 过滤器
    'rest_framework',  # rest framework
    'user.apps.UserConfig',  # 用户模块
    'record.apps.RecordConfig',  # 记录模块
    'report.apps.ReportConfig',  # 统计模块
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨域问题中间件配置  尽量放在csrf之前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sms_middleground.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sms_middleground.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sms_middleground',
        # 'HOST': '47.112.126.133',
        'HOST': '47.106.75.178',
        'PORT': 3306,
        'USER': 'root',
        # 'PASSWORD': 'XCXqwER!@34ZXcvALYHMYSQL@#TGGD875JJG!!',
        'PASSWORD': 'rzwl@2019',
        'OPTIONS': {'init_command': 'SET default_storage_engine=INNODB;'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_ROOT = '/var/www/sms_middleground/static/'
STATIC_URL = '/static/'
# 设置静态文件存放的物理目录
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 跨域问题配置
CORS_ORIGIN_ALLOW_ALL = True

# 设置上传文件的保存目录
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# HTML_ROOT = os.path.join(BASE_DIR,  'statics')

# 修改django用户类
AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    # 过滤器
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        # 'rest_framework.filters.SearchFilter',
        'my_utils.filters.MySearchFilter',
    ),
    'ORDERING_PARAM': 'order',  # 排序参数名称
    'SEARCH_PARAM': 'search',  # 搜索参数名称
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (  # 用户权限配置
        'rest_framework.authentication.BasicAuthentication',  # 浏览器调试使用
        'rest_framework.authentication.SessionAuthentication',  # 浏览器调试使用
        # 'rest_framework.authentication.TokenAuthentication',  # 前后端分离使用 全局token验证  不合理  被局部验证替代
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',  # JWT用户认证
    ),
    # 'DEFAULT_THROTTLE_CLASSES': (  # 请求限制类
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ),
    'DEFAULT_THROTTLE_RATES': {  # 限制配置
        'anon': '600/minute',
        'user': '600/minute',
        'white': '600/minute',
    },
}

import datetime

# JWT 配置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),  # 过期时间
    'JWT_AUTH_HEADER_PREFIX': 'JWT',  # 认证方式
    'JWT_ALLOW_REFRESH': True,  # 是否可以刷新未过期token
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),  # 刷新令牌的时间
    # 'JWT_RESPONSE_PAYLOAD_HANDLER': '',  # 自定义字段
}

# 自定义用户认证函数
AUTHENTICATION_BACKENDS = (
    'apps.user.views.CustomBackend',
)

# 手机号码正则表达式
REGEX_MOBILE = r'^1[3589]\d{9}$|^147\d{8}$|^176\d{8}$'

# 邮箱正则表达式
REGEX_MAIL = r'^[A-Za-z0-9\u4e00-\u9fa5]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$'

# 默认阿里云账号AccessKeyId
ACCESS_KEY_ID = 'LTAItp2WNQxl2jWQ'
# ACCESS_KEY_ID = 'wx1d71770eed52fa51'  # 锐掌
# 默认阿里云账号AccessKeySecret
ACCESS_KEY_SECRET = '4S9ya2DW33JJSvBcDtJh9FerwPwYTC'
# ACCESS_KEY_SECRET = 'dfc9e616eb2c52c6a79f226c408020fb'  # 锐掌

# 批量短信失败触发边界
LIMIT = 1000
# 失败数量/每limit
FAIL_NUM = 5

# 短信测试开关
SMS_DEBUG = False
