# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='精确到秒', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='精确到秒', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除标识', verbose_name='删除标记')),
                ('type', models.CharField(choices=[('day', '自然日'), ('mouth', '自然月')], help_text='day|自然日;mouth|自然月;', max_length=30, verbose_name='统计类型')),
                ('chart_json', models.CharField(blank=True, help_text='统计后的数据集合', max_length=1000, null=True, verbose_name='数据json字符串')),
            ],
            options={
                'verbose_name_plural': '数据统计',
                'db_table': 'report',
                'verbose_name': '数据统计',
            },
        ),
    ]
