# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default='2019-07-11', help_text='统计以天为单位', verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='debug',
            field=models.IntegerField(default=0, help_text='当日错误数', verbose_name='调试数'),
        ),
        migrations.AddField(
            model_name='report',
            name='error',
            field=models.IntegerField(default=0, help_text='当日调试数', verbose_name='错误数'),
        ),
        migrations.AddField(
            model_name='report',
            name='fail',
            field=models.IntegerField(default=0, help_text='当日失败数', verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='report',
            name='fail_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='当日失败率(失败/总数)', max_digits=5, verbose_name='失败率'),
        ),
        migrations.AddField(
            model_name='report',
            name='real_fail_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='当日实际失败率((失败+错误)/实际总数)', max_digits=5, verbose_name='实际失败率'),
        ),
        migrations.AddField(
            model_name='report',
            name='real_success_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='当日实际成功率((成功+调试+预警)/实际总数)', max_digits=5, verbose_name='实际成功率'),
        ),
        migrations.AddField(
            model_name='report',
            name='real_total',
            field=models.IntegerField(default=0, help_text='当日总数+调试+错误+预警', verbose_name='实际总数'),
        ),
        migrations.AddField(
            model_name='report',
            name='success',
            field=models.IntegerField(default=0, help_text='当日成功数', verbose_name='成功数'),
        ),
        migrations.AddField(
            model_name='report',
            name='success_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='当日成功率(成功/总数)', max_digits=5, verbose_name='成功率'),
        ),
        migrations.AddField(
            model_name='report',
            name='total',
            field=models.IntegerField(default=0, help_text='当日总数(成功+失败)', verbose_name='总数'),
        ),
        migrations.AddField(
            model_name='report',
            name='warn',
            field=models.IntegerField(default=0, help_text='当日预警数', verbose_name='预警数'),
        ),
    ]
