# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 17:03
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='精确到秒', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='精确到秒', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除标识', verbose_name='删除标记')),
                ('username', models.CharField(help_text='最大长度150字符', max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='最大长度128字符', max_length=128, verbose_name='密码')),
                ('name', models.CharField(help_text='最大长度30字符', max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', help_text='male：男 female：女', max_length=6, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, help_text='合法11位手机号码', max_length=11, null=True, verbose_name='电话号码')),
                ('email', models.CharField(blank=True, help_text='合法电子邮箱', max_length=320, null=True, verbose_name='电子邮箱')),
                ('birthday', models.DateField(blank=True, help_text='生日', null=True, verbose_name='生日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'verbose_name': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='精确到秒', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='精确到秒', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除标识', verbose_name='删除标记')),
                ('name', models.CharField(help_text='最大长度30字符', max_length=30, unique=True, verbose_name='姓名')),
                ('mobile', models.CharField(help_text='余额不足提醒时就收短信号码', max_length=11, verbose_name='电话号码')),
                ('push_num', models.IntegerField(default=0, help_text='消息推送可用次数', verbose_name='可推送次数')),
                ('pushed_num', models.IntegerField(default=0, help_text='消息推送已经使用次数', verbose_name='已推送次数')),
                ('warn_limit', models.IntegerField(default=0, help_text='达到给界限将发送充值提醒', verbose_name='预警界限')),
                ('is_infinite', models.BooleanField(default=True, help_text='是否无推送次数限制', verbose_name='是否无推送次数限制')),
                ('access_key_id', models.CharField(help_text='阿里账号AccessKeyId', max_length=30, verbose_name='AccessKeyId')),
                ('access_key_secret', models.CharField(help_text='阿里账号AccessKeySecret', max_length=30, verbose_name='AccessKeySecret')),
                ('sign_name', models.CharField(help_text='阿里短信签名', max_length=30, verbose_name='短信签名')),
                ('secret_key', models.CharField(help_text='消息推送验证标识', max_length=36, unique=True, verbose_name='密钥')),
            ],
            options={
                'verbose_name_plural': '客户',
                'db_table': 'client',
                'verbose_name': '客户',
            },
        ),
    ]
