# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-11 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_infinite',
        ),
    ]
