# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_client_is_infinite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_key_secret',
            field=models.CharField(blank=True, help_text='阿里账号AccessKeySecret', max_length=30, null=True, verbose_name='AccessKeySecret'),
        ),
        migrations.AlterField(
            model_name='client',
            name='access_key_id',
            field=models.CharField(blank=True, help_text='阿里账号AccessKeyId', max_length=30, null=True, verbose_name='AccessKeyId'),
        ),
    ]
