# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-19 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190711_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.ForeignKey(blank=True, help_text='账号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='账号'),
        ),
    ]
