# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-19 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_client_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='user',
        ),
    ]
